Properties of Arrays 

In [7]:
import numpy as np

Shape is a property it gets the shape of array ( number of rows and number of columns )   [Rows and Cloumns]

In [15]:
data = np.array([
    [1 ,2 , 3 , 4 , 5],
    [6 ,4 , 9 , 10 , 3]
])
print(data.shape)
print(data.ndim)
print(data.size)
print(data.dtype)




(2, 5)
2
10
int64


Array Reshaping

In [23]:
array = np.arange(12)
print("Original Array =" ,array)


reshape_array = array.reshape((3, 4))
print(reshape_array)

flatend = reshape_array.flatten()
print(flatend)

raveled = reshape_array.ravel()
print(raveled)

## ravel() method returns view instead of copy's the array  --original array


Original Array = [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
matrix = np.array([
    [1 , 2 , 3 , 4],
    [5 , 6 , 7 , 8],
    [9 , 5 , 2 , 4],
    [6 , 8 , 9 , 1]
])
print(matrix)
print("\n")
transpose = matrix.transpose()
print(transpose)
print("\n")
T = matrix.T
print(T)

[[1 2 3 4]
 [5 6 7 8]
 [9 5 2 4]
 [6 8 9 1]]


[[1 5 9 6]
 [2 6 5 8]
 [3 7 2 9]
 [4 8 4 1]]


[[1 5 9 6]
 [2 6 5 8]
 [3 7 2 9]
 [4 8 4 1]]
