## Numpy array and basics
lwarn about numpy

In [ ]:
import numpy as np


## 1-Dimensional arrays

In [ ]:

data = np.array([10 , 20 , 30 , 40 , 50])
print("1-D array",data)


1-D array [10 20 30 40 50]


## 2-dimensional arrays


In [ ]:
data_2d = np.array([
    [10 , 20 , 30],
    [99 , 44 , 76],
    [42 , 23 , 91]
    ])
print(data_2d)

[[10 20 30]
 [99 44 76]
 [42 23 91]]



Multi Dimensional Arrays


In [ ]:
multiDim_array = np.array([
    [10 , 77 , 89 , 10],
    [12 , 65 , 89 , 19],
    [12 , 31 , 71 , 78],
    [10 , 16 , 81 , 44]
])
print(multiDim_array)

[[10 77 89 10]
 [12 65 89 19]
 [12 31 71 78]
 [10 16 81 44]]


Lists and numpy arrays

In [ ]:
py_list = [10 , 7 , 8 , 31]
print("Python list Multiplication",py_list * 2)

Python list Multiplication [10, 7, 8, 31, 10, 7, 8, 31]


In [ ]:
numpy_array = np.array([10 , 7 , 8 , 31])
print("Numpy Array multiplication = ", numpy_array * 2)


Numpy Array multiplication =  [20 14 16 62]


In [16]:
import time
start = time.time()
python_list = [i*2 for i in range(100000000)]
print("Python List Time = " ,time.time() - start)

start = time.time()
numpy_array = np.arange(100000000) * 2
print("Numpy Array Time = " ,time.time() - start)

Python List Time =  7.421946287155151
Numpy Array Time =  0.493807315826416
