## Numpy array and basics
lwarn about numpy

In [7]:
import numpy as np


## 1-Dimensional arrays

In [9]:

data = np.array([10 , 20 , 30 , 40 , 50])
print("1-D array",data)


1-D array [10 20 30 40 50]


## 2-dimensional arrays


In [11]:
data_2d = np.array([
    [10 , 20 , 30],
    [99 , 44 , 76],
    [42 , 23 , 91]
                ])
print(data_2d)

[[10 20 30]
 [99 44 76]
 [42 23 91]]
